name: 'Lerna publish action'
description: 'Publish repositories managed with Lerna'
inputs:
  bump:
    description: "Semver value to bump. Values major|minor|patch"
    required: true
  auth-token-string:
    description: "Registry's auth token string that injected to .npmrc before running lerna"
    required: true
  registry:
    description: "Registery where to publish"
    default: "https://registry.npmjs.org/"
outputs: {}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bump }}
    - ${{ inputs.auth-token }}
    - ${{ inputs.registry }}
