name: 'Lerna publish action'
description: 'Publish repositories managed with Lerna'
inputs:
  bump:
    description: "Semver value to bump. Values major|minor|patch"
    required: true
  registry:
    description: "Registery where to publish"
    default: "https://registry.npmjs.org/"
    required: false
  extra_arguments:
    description: "Extra arguments for Lerna"
    required: false
outputs: {}
runs:
  using: 'docker'
  image: 'Dockerfile'
